<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../../style.css" rel="stylesheet" type="text/css">
    <title>automating test generation</title>
</head>
<body>
<br>
<div class = "center">
    <a href="../../index.html" style="text-decoration: none;"><b>BJORN MADSEN'S WEBSITE</b><br></a>
    <hr id="hrid"/>
    <div style="text-align: center; display: inline-block; width: 100%;">
        <a class="title" href="../../about.html">ABOUT</a> &nbsp;
        <a class="title" href="../../contact.html">EMAIL</a> &nbsp;
        <a class="title" href="https://paypal.me/BjornMadsen">DONATE</a>
    </div>
</div>
    <br><br>
    <div style="margin-bottom: 3ch;text-transform: none;"></div>

<div style="margin-bottom: 3ch;text-transform: none;">2020-06-07</div><div class="heading">automating test generation</div><hr/>    
<p>When writing tests by hand, it's often a challenge to cover all combinations of inputs.
So don't. Let python do that for you.</p>
<p>Here's an example.<br />
I have a function that I'd like to test for various inputs. It works for what I intended, 
but I'd like to check all the cases where the code raises an exception.</p>
<pre><code>def adder(a, b):  # function to test.
    """ adds a to b"""
    return a + b
</code></pre>
<p>The input options are integers, floats, lists and strings:</p>
<pre><code>options = [9, 9.0, [9], "9"]
</code></pre>
<p>I also need a template that reflects the test I would write, should I have written it by hand:</p>
<pre><code>test_template = """

def test_adder_{}():
    _ = adder{}
"""
</code></pre>
<p>With these three components, I can now generate my tests automatically and write any that fail out automatically.</p>
<pre><code>from pathlib import Path
from itertools import product


def test_discovery():
    test_number = 0
    for c in product(*[options, options]):  # the cartesian product of all inputs.
        test_number += 1  
        try:  
            adder(*c)  # the exercise of my target function
        except Exception:
            new_test = test_template.format(test_number, c)   # formatting of the test template to a test.
            with Path(__file__).open('a') as fo:  # appending the test to this script.
                fo.write(new_test)
</code></pre>
<p>When the function <code>test_discovery</code>, above, is called, it will <strong>append</strong> the tests that 
raise <code>exception</code>, like this:</p>
<pre><code>test_discovery()


def test_adder_3():
    _ = adder(9, [9])


def test_adder_4():
    _ = adder(9, '9')


def test_adder_7():
    _ = adder(9.0, [9])


def test_adder_8():
    _ = adder(9.0, '9')


def test_adder_9():
    _ = adder([9], 9)


def test_adder_10():
    _ = adder([9], 9.0)


def test_adder_12():
    _ = adder([9], '9')


def test_adder_13():
    _ = adder('9', 9)


def test_adder_14():
    _ = adder('9', 9.0)


def test_adder_15():
    _ = adder('9', [9])
</code></pre>
<p>As you may notice, the test name numbers are not chronological, as the tests that 
pass have not been written.</p>
<p>Neat he? </p>
<p>The code is available (as usual) in <a href="example.py">example.py</a></p>

</body>
</html>
